name: eco_angler
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  introduction_screen: ^3.1.17
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  provider: ^6.1.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  http: ^1.2.1
  geolocator: ^14.0.1
  youtube_player_flutter: ^9.1.1
  camera: ^0.10.5
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logotrans.png"  # Replace with your icon path
  adaptive_icon_background: "#ffffff"     # Optional for Android


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/cc.png
    - assets/on1.png
    - assets/on2.png
    - assets/on3.png
    - assets/food1.jpeg
    - assets/food2.jpeg
    - assets/food3.jpeg
    - assets/food4.jpeg
    - assets/food5.jpeg
    - assets/food6.jpeg
    - assets/food7.jpeg
    - assets/food8.jpeg
    - assets/food9.jpeg
    - assets/food10.jpeg
    - assets/food11.jpeg
    - assets/food12.jpg
    - assets/cm1.jpeg
    - assets/cm2.jpeg
    - assets/cm3.jpeg
    - assets/cm4.jpeg
    - assets/logotrans.png
    - assets/fish.png
    - assets/lion.jpg
    - assets/fish1.jpg
    - assets/fish2.jpg
    - assets/fish3.jpg
    - assets/fish4.jpg
    - assets/fish5.jpg
    - assets/fish6.jpg
    - assets/fish7.jpg
    - assets/fish8.webp
    - assets/fish9.jpg
    - assets/fish10.webp
    - assets/fish11.jpg
    - assets/fish12.jpg
